### PR TITLE
edmonton to Van Airbnb

### LINKED ISSUE #10: vancouver to edmonton
we have decided to use the Edmonton housing dataset for our dashboard, this PR should replace the vancouver context to edmonton and load the dataset.

### PR DESCRIPTION
**Pull request by wenyunie**
…data description accordingly

### CODE REVIEW

**Comment by wenyunie** [comment]
1. changed from vancouver to edmonton
2. changed section 2 
3. loaded the edmonton housing tax data

**Review by jlee2843 — APPROVED** [review]
LGTM!

**Comment by wenyunie** [comment]
According to the discussion yesterday, we changed our data to vancouver airbnb, this PR will be refreshed to that direction.

**Comment by wenyunie** [comment]
changed from edmonton to vancouver airbnb
changed section 2 accordingly
loaded the vancouver airbnb data (only the data for the latest quarter as an example, full data pending)

**Pull request merged**
